# Keep this file secure and out of version control
database:
  host: "database-1.cpakuqeqgh9q.us-east-1.rds.amazonaws.com"
  secret_name: "rds!db-ef989dd0-975a-4c33-ab17-69f8ef4e03a1"
  region_name: "us-east-1"
  # The specific database to connect to
  db_name: 'ry-vue'