---
# Dynamic Database Configuration for Robot Webhook API
# Main database is hardcoded, project databases are dynamically resolved

# Main control database (hardcoded)
main_database: "ry-vue"

# List of databases that need notifications (can include dynamic ones)
notification_needed:
  - "project"

# Table configurations
# Use "main" for main database
# "project" for dynamically resolved project databases
tables:
  # Robot Status/Pose/Power updates go to management table
  robot_status:
    - database: "project"
      table_name: "mnt_robots_management"
      primary_keys: ["robot_sn"]
      fields: null
      description: "Robot status table in project database"

  robot_work_location:
    - database: "project"
      table_name: "mnt_robots_work_location"
      primary_keys: ["robot_sn"]
      fields: null
      description: "Robot work location table in project database"

  # Robot Events/Errors go to events table
  robot_events:
    - database: "project"
      table_name: "mnt_robot_events"
      primary_keys: ["robot_sn", "event_id"]
      fields: null
      description: "Robot events table in project database"
