---
# Database Configuration for Webhook API
databases:
  - "foxx_irvine_office"
  - "foxx_irvine_office_test"


# List of databases that notification is needed
notification_needed:
  - "foxx_irvine_office"

tables:
  # Robot Status/Pose/Power updates go to management table
  robot_status:
    - database: "foxx_irvine_office"
      table_name: "mnt_robots_management"
      primary_keys: ["robot_sn"]
      fields: null
      description: "Main robot status table in foxx_irvine_office database"

    - database: "foxx_irvine_office_test"
      table_name: "mnt_robots_management"
      primary_keys: ["robot_sn"]
      fields: null
      description: "Robot status table in foxx test database"

  # Robot Events/Errors go to events table
  robot_events:
    - database: "foxx_irvine_office"
      table_name: "mnt_robot_events"
      primary_keys: ["robot_sn", "event_id"]
      fields: null
      description: "Robot events table in foxx_irvine_office database"

    - database: "foxx_irvine_office_test"
      table_name: "mnt_robot_events"
      primary_keys: ["robot_sn", "event_id"]
      fields: null
      description: "Robot events table in foxx test database"
