# Keep this file secure and out of version control
database:
  host: 'jj9d30usfx.us-east-1.aws.clickhouse.cloud'
  user: 'default'
  password: 'wwnW_zsKm0hhQ'
  # Set to false if not using a secure connection
  secure: True