---
# Database Configuration for Robot Data Pipeline
# This file defines which tables to write to in which databases

# List of all databases used
databases:
  - "foxx_irvine_office"
  - "foxx_irvine_office_test"

# List of databases that notification is needed
notification_needed:
  - "foxx_irvine_office"

# Table configurations grouped by data type
tables:
  # Location Table
  location:
    - database: "foxx_irvine_office"
      table_name: "pro_building_info"
      primary_keys: ["building_id"]
      fields: null  # Use all fields from the DataFrame
      description: "Building info table in foxx irvine office database"

    - database: "foxx_irvine_office_test"
      table_name: "pro_building_info"
      primary_keys: ["building_id"]
      fields: null
      description: "Building info table in foxx test database"

  # Robot Status Table
  robot_status:
    - database: "foxx_irvine_office"
      table_name: "mnt_robots_management"
      primary_keys: ["robot_sn"]
      fields: null  # Use all fields from the DataFrame
      description: "Main robot status table in foxx irvine office database"

    - database: "foxx_irvine_office_test"
      table_name: "mnt_robots_management"
      primary_keys: ["robot_sn"]
      fields: null
      description: "Robot status table in foxx test database"

  # Robot Task Tables
  robot_task:
    - database: "foxx_irvine_office"
      table_name: "mnt_robots_task"
      primary_keys: ["robot_sn", "task_name", "start_time"]
      fields: null  # Use all fields from the DataFrame
      description: "Main robot task tracking table in foxx irvine office db"

    - database: "foxx_irvine_office_test"
      table_name: "mnt_robots_task"
      primary_keys: ["robot_sn", "task_name", "start_time"]
      fields: null
      description: "Robot task tracking table in test database"

  # Robot Task Overview Tables - not used
  robot_task_overview:
    - database: "foxx_irvine_office"
      table_name: "mnt_robots_task_overview"
      primary_keys: ["robot_sn", "day", "hour"]
      fields: null
      description: "Hourly task overview aggregation in foxx irvine office db"

    - database: "foxx_irvine_office_test"
      table_name: "mnt_robots_task_overview"
      primary_keys: ["robot_sn", "day", "hour"]
      fields: null
      description: "Hourly task overview aggregation in foxx test database"

  # Robot Charging Tables
  robot_charging:
    - database: "foxx_irvine_office"
      table_name: "mnt_robots_charging_sessions"
      primary_keys: ["robot_sn", "start_time", "end_time"]
      fields: null
      description: "Robot charging session data in foxx irvine office database"

    - database: "foxx_irvine_office_test"
      table_name: "mnt_robots_charging_sessions"
      primary_keys: ["robot_sn", "start_time", "end_time"]
      fields: null
      description: "Robot charging session data in foxx test database"

  # Robot Events Tables
  robot_events:
    - database: "foxx_irvine_office"
      table_name: "mnt_robot_events"
      primary_keys: ["robot_sn", "event_id"]
      fields: null
      description: "Robot events and errors in foxx irvine office database"

    - database: "foxx_irvine_office_test"
      table_name: "mnt_robot_events"
      primary_keys: ["robot_sn", "event_id"]
      fields: null
      description: "Robot events and errors in foxx test database"

  # Robot Work Location Tables
  robot_work_location:
    - database: "foxx_irvine_office"
      table_name: "mnt_robots_work_location"
      primary_keys: ["robot_sn"]
      fields: null
      description: "Robot work location tracking in foxx irvine office database"

    - database: "foxx_irvine_office_test"
      table_name: "mnt_robots_work_location"
      primary_keys: ["robot_sn"]
      fields: null
      description: "Robot work location tracking in foxx test database"

  # Floor Info Tables
  floor_info:
    - database: "foxx_irvine_office"
      table_name: "pro_floor_info"
      primary_keys: ["floor_id"]
      fields: null
      description: "Floor information in foxx irvine office database"

    - database: "foxx_irvine_office_test"
      table_name: "pro_floor_info"
      primary_keys: ["floor_id"]
      fields: null
      description: "Floor information in foxx test database"

  # Map Floor Mapping Tables
  map_floor_mapping:
    - database: "foxx_irvine_office"
      table_name: "mnt_robot_map_floor_mapping"
      primary_keys: ["id"]
      fields: null
      description: "Map to floor mapping in foxx irvine office database"

    - database: "foxx_irvine_office_test"
      table_name: "mnt_robot_map_floor_mapping"
      primary_keys: ["id"]
      fields: null
      description: "Map to floor mapping in foxx test database"

  # Main Database Tables (ry-vue equivalent)
  main_building_info:
    - database: "ry-vue"  # This can be changed in config
      table_name: "pro_building_info"
      primary_keys: ["building_id"]
      fields: null
      description: "Building info in main database"

  main_project_info:
    - database: "ry-vue"  # This can be changed in config
      table_name: "pro_project_info"
      primary_keys: ["project_id"]
      fields: null
      description: "Project info in main database"

  tenant_resource:
    - database: "ry-vue"  # This can be changed in config
      table_name: "sys_tenant_resource"
      primary_keys: ["tenant_id", "resource_type", "resource_key"]
      fields: null
      description: "Tenant resource mapping in main database"
      
  # Support Tickets Tables
  support_tickets_timeline:
    - database: "foxx_irvine_office_test"
      table_name: "mnt_robot_report_timeline"
      primary_keys: ["id"]
      fields: null
      description: "Support ticket timeline monitoring"
      read_only: false

    - database: "foxx_irvine_office"
      table_name: "mnt_robot_report_timeline"
      primary_keys: ["id"]
      fields: null
      description: "Support ticket timeline monitoring"
      read_only: false

  support_tickets:
    - database: "foxx_irvine_office_test"
      table_name: "mnt_robot_event_reports"
      primary_keys: ["id"]
      fields: null
      description: "Support ticket event reports"
      read_only: false

    - database: "foxx_irvine_office"
      table_name: "mnt_robot_event_reports"
      primary_keys: ["id"]
      fields: null
      description: "Support ticket event reports"
      read_only: false
