# Alert Service Configuration
# ===========================

# Database connections
database:
  rds:
    # Directory where rds/credentials.yaml is located
    config_dir: 'alert/config/rds'
  clickhouse:
    # Directory where clickhouse/credentials.yaml is located
    config_dir: 'alert/config/clickhouse'

# Performance optimization settings
optimization:
  batch_size: 10                    # Process 10 targets at once
  max_workers: 8                    # Use 8 parallel workers each hand
  use_multiprocessing: false        # false => threading (better for I/O)
  batch_db_operations: true         # Batch database saves; Should always be true

# Logging configuration (in run.py)
logging:
  level: 'INFO'
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"