name: "Restrooms"
square_footage: 12500

weights:
  PM2.5: 0.05
  PM10: 0.05
  NH3: 0.25
  H2S: 0.25
  tVOC: 0.15
  Temperature: 0.10
  Humidity: 0.15

thresholds:
  - parameter: "PM2.5"
    ranges:
      - range: [0, 10]
        score: 100
      - range: [10, 12]
        score: 90
      - range: [12, 15]
        score: 80
      - range: [15, 25]
        score: 60
      - range: [25, 35]
        score: 40
      - range: [35, "inf"]
        score: 20

  - parameter: "PM10"
    ranges:
      - range: [0, 20]
        score: 100
      - range: [20, 30]
        score: 90
      - range: [30, 50]
        score: 80
      - range: [50, 75]
        score: 60
      - range: [75, 100]
        score: 40
      - range: [100, "inf"]
        score: 20

  - parameter: "NH3"
    ranges:
      - range: [0, 0.5]
        score: 100
      - range: [0.5, 1]
        score: 80
      - range: [1, 5]
        score: 60
      - range: [5, 10]
        score: 40
      - range: [10, "inf"]
        score: 20

  - parameter: "H2S"
    ranges:
      - range: [0, 0.03]
        score: 100
      - range: [0.03, 0.1]
        score: 80
      - range: [0.1, 0.5]
        score: 60
      - range: [0.5, 2]
        score: 40
      - range: [2, "inf"]
        score: 20

  - parameter: "tVOC"
    ranges:
      - range: [0, 200]
        score: 100
      - range: [200, 300]
        score: 90
      - range: [300, 500]
        score: 70
      - range: [500, 750]
        score: 50
      - range: [750, 1000]
        score: 30
      - range: [1000, "inf"]
        score: 10

  - parameter: "Temperature"
    ranges:
      - range: [19, 26]
        score: 100
      - range: [17, 19]
        score: 80
      - range: [26, 28]
        score: 80
      - range: [15, 17]
        score: 60
      - range: [28, 30]
        score: 60
      - range: [12, 15]
        score: 40
      - range: [30, 32]
        score: 40
      - range: [0, 12]
        score: 20
      - range: [32, "inf"]
        score: 20

  - parameter: "Humidity"
    ranges:
      - range: [30, 60]
        score: 100
      - range: [20, 30]
        score: 80
      - range: [60, 70]
        score: 60
      - range: [10, 20]
        score: 40
      - range: [70, 80]
        score: 30
      - range: [0, 10]
        score: 20
      - range: [80, 100]
        score: 20